#!/bin/sh
# Pull the live Home Assistant /config into HomeAssistant/config, so that every
# later change is a reviewable git diff instead of a hand edit on the box.
#
#   sh HomeAssistant/tools/ha_pull.sh
#
# Read-only against the box: it runs one `tar czf -` over the SSH pipe. Nothing
# is written to /config.
#
# Override the host with HA_SSH=<alias> if the `ha` alias in ~/.ssh/config is
# not the one you want.
set -eu

mod_dir=$(cd "$(dirname "$0")/.." && pwd)
dest="$mod_dir/config"
state="$mod_dir/.state"
tmp="$state/pull-tmp"
host=${HA_SSH:-ha}

mkdir -p "$state"
rm -rf "$tmp"
mkdir -p "$tmp"

# Built one line at a time rather than as a backslash-continued tar invocation,
# so each exclusion can say why it is there. Single quotes around the globs are
# literal in this variable and are stripped by the remote shell, which keeps it
# from glob-expanding them against its own cwd.
ex=""
# Secrets. Every one of these would be a credential leak in a git commit.
ex="$ex --exclude=./secrets.yaml"          # every credential the config references
ex="$ex --exclude=./google_key.json"       # a GCP service-account private key
ex="$ex --exclude=./.storage"              # `auth` = every session token; core.config_entries = integration passwords
ex="$ex --exclude=./zigbee2mqtt"           # its configuration.yaml holds the MQTT password AND the Zigbee network key
# Bulk that is not config.
ex="$ex --exclude=./custom_components"     # 52 MB, HACS-managed (hacs, midea_ac_lan), reinstallable
ex="$ex --exclude=./deps"
ex="$ex --exclude=./tts"
ex="$ex --exclude=./.cloud"
ex="$ex --exclude=./backups"
ex="$ex --exclude=./image"
ex="$ex --exclude=./media"
ex="$ex --exclude='*.db'"
ex="$ex --exclude='*.db-shm'"
ex="$ex --exclude='*.db-wal'"
ex="$ex --exclude='*.log'"
ex="$ex --exclude='*.log.*'"
ex="$ex --exclude='*.tar'"
ex="$ex --exclude=__pycache__"
ex="$ex --exclude=./.cache"                # HA's downloaded brand-icon cache; pure noise
ex="$ex --exclude=./.ha_run.lock"          # runtime lock
ex="$ex --exclude=./dtek/.cache.json"      # dtek_poll.py session cookie + last good payload; regenerates itself
ex="$ex --exclude=./.irbridge-last-backup" # pointer written by ha_deploy.sh
# Backups of config, which are not loaded and would double every diff.
ex="$ex --exclude='./irbridge-backup-*'"   # rollback points ha_deploy.sh leaves behind
ex="$ex --exclude='./rename*-backup-*'"    # rollback points from the entity-id rename procedure (README); each holds a full core.entity_registry
ex="$ex --exclude='*.bak-*'"               # stray hand-made backups

echo "pulling /config from $host ..." >&2
ssh -o BatchMode=yes "$host" "tar czf - -C /config $ex ." | tar xzf - -C "$tmp"

# A pull that produced no configuration.yaml went wrong; keep the old mirror.
if [ ! -f "$tmp/configuration.yaml" ]; then
    echo "FAILED: no configuration.yaml in the pull - mirror left untouched" >&2
    exit 1
fi

# Refuse to install a mirror containing anything from the secrets list above.
for leaked in secrets.yaml google_key.json .storage zigbee2mqtt; do
    if [ -e "$tmp/$leaked" ]; then
        echo "REFUSING: '$leaked' made it into the pull" >&2
        exit 1
    fi
done

# Swap rather than extract-over, so files deleted on the box show up as
# deletions in git instead of lingering in the mirror forever.
rm -rf "$dest"
mv "$tmp" "$dest"

# The three registries, named explicitly. core.config_entries is NOT pulled: it
# carries integration credentials. Audit inputs only; .state is gitignored.
for reg in core.entity_registry core.device_registry core.area_registry; do
    if ssh -o BatchMode=yes "$host" "cat /config/.storage/$reg" > "$state/$reg.json" 2>/dev/null; then
        echo "  registry: $reg.json" >&2
    else
        rm -f "$state/$reg.json"
        echo "  registry: $reg MISSING" >&2
    fi
done

# Dashboards. Also out of .storage, but unlike the registries these ARE
# committed, in their own directory rather than in the gitignored .state.
#
# The reason for the split: a registry is derived state, regenerated by HA from
# the devices it finds, and mostly noise in a diff. A Lovelace layout is the
# opposite — hand-built, reproducible from nothing else in this repo, and lost
# for good if the box dies. It is the one thing here that was genuinely
# unbacked. They carry no credentials: entity ids and card options, which
# configuration.yaml already commits by the hundred.
#
# Discovered by prefix rather than named, so a dashboard added later starts
# being mirrored without touching this script. HA writes .storage
# pretty-printed, so these land verbatim and still produce a readable diff, and
# a file copied back is valid input — json.loads does not care about the
# whitespace HA would have written.
dash="$mod_dir/dashboards"
dash_tmp="$state/dash-tmp"
rm -rf "$dash_tmp"
mkdir -p "$dash_tmp"

# `.bak-` is filtered for the same reason the tar exclude list drops '*.bak-*':
# a hand-made rollback copy is not a dashboard HA serves, and mirroring one
# puts a stale layout in git looking exactly like a live one.
dash_ok=1
for f in $(ssh -o BatchMode=yes "$host" "ls /config/.storage/ 2>/dev/null | grep '^lovelace' | grep -v '\.bak-'"); do
    if ssh -o BatchMode=yes "$host" "cat /config/.storage/$f" > "$dash_tmp/$f.json" 2>/dev/null; then
        echo "  dashboard: $f.json" >&2
    else
        echo "  dashboard: $f FAILED" >&2
        dash_ok=0
    fi
done

# Swap only on a clean sweep. A half-failed pull must not silently delete a
# dashboard from the mirror — that would read as "the user removed it" in the
# diff, and the backup would be gone at the moment it was needed.
if [ "$dash_ok" = 1 ]; then
    rm -rf "$dash"
    mv "$dash_tmp" "$dash"
else
    rm -rf "$dash_tmp"
    echo "  dashboards: pull incomplete - mirror left untouched" >&2
fi

echo >&2
echo "mirrored $(find "$dest" -type f | wc -l | tr -d ' ') files into HomeAssistant/config" >&2
echo "now: git status --short" >&2
